cache: bundler
language: ruby
rvm:
- jruby-1.7.27
- 2.1.10
- 2.2.7
- jruby-9.1.14.0
- 2.3.4
- 2.4.1
- ruby-head
- jruby-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: jruby-9.1.14.0
  - rvm: 2.1.10
  - rvm: 2.3.4
  - rvm: ruby-head
  - rvm: jruby-head
  - env: CELLULOID_BACKPORTED=true
  - env: CELLULOID_BACKPORTED=false CELLULOID_LEAKTEST=true
  - env: CELLULOID_BACKPORTED=false CELLULOID_TASK_CLASS=Threaded
  - env: CELLULOID_BACKPORTED=true CELLULOID_TASK_CLASS=Threaded
env:
  global:
  - NUMBER_OF_PROCESSORS=4 CELLULOID_CONFIG_FILE=.env-ci
  matrix:
  - CELLULOID_BACKPORTED=true
  - CELLULOID_BACKPORTED=false
  - CELLULOID_BACKPORTED=false CELLULOID_LEAKTEST=true
  - CELLULOID_BACKPORTED=false CELLULOID_TASK_CLASS=Threaded
  - CELLULOID_BACKPORTED=true CELLULOID_TASK_CLASS=Threaded
notifications:
  irc: irc.freenode.org#celluloid
  slack:
    secure: uJ8uoiNgiEDoRewbH6gj9mphUGVDtjXeEy8++vSTQkLqIkkoZ3M+mr0yldL2/ECaG8wHLH2035DHM4d54GyeVEU/8UG80UVAnYTctlzzjn1rfXPfCIsZDXYMUjXe3wvOouN+b4hjiyXe7ZsssdRoeKw6rHIU8/tUHgC3IfZel7s=
sudo: false
before_install:
  - gem update --system
  - gem install bundler
install: bundle install --without=development
