script: rake ci
language: ruby
rvm:
  - 2.2.0
  - 2.2.2
  - jruby
  - ruby-head
  - jruby-head
  - rbx-2

# TODO: Put these back:
# * CELLULOID_TASK_CLASS=Fibered
# * CELLULOID_TASK_CLASS=Threaded
# For right now the imporant thing is to test BACKPORTED mode:

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
    - env: CELLULOID_BACKPORTED=true
    - env: CELLULOID_BACKPORTED=false CELLULOID_LEAKTEST=1

env:
  global:
    - NUMBER_OF_PROCESSORS=2 CELLULOID_CONFIG_FILE=.env-ci
  matrix:
    - CELLULOID_BACKPORTED=true
    - CELLULOID_BACKPORTED=false
    - CELLULOID_BACKPORTED=false CELLULOID_LEAKTEST=1

notifications:
  irc: "irc.freenode.org#celluloid"

before_install:
  # Only use 1 job until Travis fixes the rbx --jobs issue.
  - if [ "$TRAVIS_RUBY_VERSION" == "rbx-2" ] ; then export BUNDLE_JOBS=1 ; else export BUNDLE_JOBS=4; fi

sudo: false
install: bundle install --without=development